services:
  backend:
    build: .
    environment:
      DATABASE_URL: sqlite://db.sqlite3
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./secrets.json
        target: /app/secrets.json
        read_only: true
      - type: bind
        source: ./db.sqlite3
        target: /app/db.sqlite3
        read_only: false
