[package]
name = "migrator"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true

rusqlite = { version = "0.32.1", features = ["bundled"] }
rustc-stable-hash = "0.1.1"
