[package]
name = "migrator"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
sqlx.workspace = true

rustc-stable-hash = "0.1.1"
